# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.10"

  # config.vm.box_check_update = true

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 50070, host: 50070
  config.vm.network "forwarded_port", guest: 8088, host: 8088

  # Create a private network, which allows host-only access to the machine
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, generally bridged mode
  # config.vm.network "public_network"

  # usage: <host_folder>, <guest_mount> [, opts ]
  config.vm.synced_folder "../../cache", "/_host_cache"
  config.vm.synced_folder "./root/HADOOP_HOME", "/_HADOOP_HOME"

  # Example for VirtualBox:
  # config.vm.provider "virtualbox" do |vb|
  #   vb.gui = false
  #   vb.memory = "4096"
  # end

  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y openjdk-8-jdk

    export JAVA_HOME=$(jrunscript -e 'java.lang.System.out.println(java.lang.System.getProperty("java.home"));')
    grep JAVA_HOME /etc/environment || (sudo bash -c "echo JAVA_HOME='$JAVA_HOME' >> /etc/environment")
    echo "JAVA_HOME=$JAVA_HOME"
    
    [[ -f /_host_cache/hadoop-2.7.3.tar.gz ]] && \
      (echo using cached copy && \
        cp /_host_cache/hadoop-2.7.3.tar.gz /tmp/hadoop-2.7.3.tar.gz) \
      || \
      (echo cache missing, downloading hadoop-2.7.3.tar.gz ourselves && \
        wget -nv -O /_host_cache/hadoop-2.7.3.tar.gz http://www-eu.apache.org/dist/hadoop/common/stable2/hadoop-2.7.3.tar.gz)

    echo md5sum: expected=3455bb57e4b4906bbea67b58cca78fa8 actual=$(/usr/bin/md5sum /tmp/hadoop-2.7.3.tar.gz)
    [ 3455bb57e4b4906bbea67b58cca78fa8 != "$(md5sum /tmp/hadoop-2.7.3.tar.gz  | cut -f1 -d' ')" ] && echo BAD MD5SUM && exit 1

    cd /tmp
    sudo tar zxf hadoop-2.7.3.tar.gz -C /opt
    rm /tmp/hadoop-2.7.3.tar.gz
    sudo chown -R vagrant:vagrant /opt/hadoop-2.7.3

    export HADOOP_HOME='/opt/hadoop-2.7.3'
    grep HADOOP_HOME /etc/environment || (sudo bash -c "echo HADOOP_HOME="$HADOOP_HOME" >> /etc/environment")
    echo "HADOOP_HOME=$HADOOP_HOME"

    sudo cp /_HADOOP_HOME/etc/hadoop/core-site.xml $HADOOP_HOME/etc/hadoop/core-site.xml
    sudo cp /_HADOOP_HOME/etc/hadoop/hdfs-site.xml $HADOOP_HOME/etc/hadoop/hdfs-site.xml

    # allow sshing into localhost without a passphrase
    rm /home/vagrant/.ssh/id_rsa{,.pub}
    ssh-keygen -R localhost -f /home/vagrant/.ssh/known_hosts
    ssh-keygen -t rsa -P '' -f /home/vagrant/.ssh/id_rsa
    cat ~/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    chmod 0600 ~/.ssh/authorized_keys
    echo Passphrase-less key created

    # formats HDFS
    yes | $HADOOP_HOME/bin/hdfs namenode -format
    echo HDFS formatted

    # starts NameNode and DataNode daemons
    echo yes | $HADOOP_HOME/sbin/start-dfs.sh
    echo hadoop daemons started

    # create MapReduce jobs directory
    $HADOOP_HOME/bin/hdfs dfs -mkdir /user
    $HADOOP_HOME/bin/hdfs dfs -mkdir /user/vagrant
    echo mapreduce jobs directories created

    # start YARN
    echo yes | $HADOOP_HOME/sbin/start-yarn.sh
    echo YARN started
  SHELL
end
